### ISSUE TITLE
how to add react-native-elements to web

### ISSUE THREAD

**Issue by webnah** [davidkwan95/monorepo-starter#1]
i tried to add but nebie, so please help if you can.
thank you your perfect monorepo-starter

**Comment by davidkwan95** [comment]
@webnah changing your `razzle.config.js` to the config like this gist should work https://gist.github.com/davidkwan95/205cc48270810fc80c203bc7035e806f

What it does is, it tell webpack to include those 3 packages in the compilation

**Comment by davidkwan95** [comment]
I'll add `react-native-elements` to this starter-kit if a lot of people requested it, but I'll close this issue for now
